                                
                                                                     
  
                           
                                                   
                                                    
                                        
  
                                                       
                                                                   
                                              
                                                 
                                                                          
                                                
                                                
                                                     
                                   
  
                           
                                                     
                                                              
                                                      
  
              
                                                        
                                                   
                                                
  
                                                         
                                                             
                                                        
                                                                
                                                             
                                                 
                                                             
                                                         
                                          
                                                                      
                                                                
                                                       
                                               
                                  
  
                                        
                                                 
                                                    
                                       
                                 
  
                                                    
                                                                          
                                                                           
                                                    
                                                              
                                                          
                                                    
                                              
                                                              
                                                       
                                                   
                                                   
  
                                                                   
                                                                       
   
#ifndef PURECVISOR_PCV_LIO_H
#define PURECVISOR_PCV_LIO_H

#include <glib.h>

G_BEGIN_DECLS

                                                      
                                          
                                                
#define PCV_LIO_ROOT        "/sys/kernel/config/target"

                                
                                                              
                                                         
                                                    
                                               
                                                    
                                   
                                                        
                                        
#define PCV_LIO_IQN_PREFIX  "iqn.2026-03.purecvisor"

   
                          
                                                      
                                                      
                                               
                                     
  
                                              
  
                                                                    
                   
   
gchar *pcv_lio_path_backstore(const gchar *root, const gchar *store);

   
                       
                      
                                                                
                                                                 
                                                 
                                                     
  
                                          
  
                                                             
              
   
gchar *pcv_lio_path_target(const gchar *root, const gchar *iqn);

   
                    
                      
                                                       
  
                                                 
  
                                                                    
                                                   
   
gchar *pcv_lio_path_tpg(const gchar *root, const gchar *iqn);

   
                      
                                                         
                                                         
                                   
  
                                               
  
                                                                      
                   
   
gchar *pcv_lio_iqn_for_vm(const gchar *vm_name);

   
                   
                                        
                                         
  
                                                
                                                   
           
  
                                                       
                                                         
                                                   
  
                                                  
   
gboolean pcv_lio_mkdir_p(const gchar *path, GError **error);

   
                      
                                          
                                                              
                                                                
                                                        
                                               
                                                          
                                                        
                                                             
                                                
                                           
                            
  
                                                                  
                                                          
                                                         
                                                   
                                                     
  
                                                 
                                                          
                                                           
                                                  
                                 
  
                                                 
                                                       
                                                  
                                                   
                                                      
                                                                  
                                                          
                                                              
                                            
                                                            
                                                
                                                    
                                                   
                                               
                                               
            
  
                                                 
                                                     
                              
  
                                                   
                                                                 
                                                
                   
  
                                                                 
   
gboolean pcv_lio_write_attr(const gchar *dir, const gchar *attr,
                            const gchar *value, GError **error);

   
                     
                      
                          
  
                                                       
                                                       
                                              
  
                                                   
   
gchar *pcv_lio_read_attr(const gchar *dir, const gchar *attr);

   
                 
                      
                            
  
                                               
                         
  
                                                  
   
gboolean pcv_lio_rmdir(const gchar *path, GError **error);

   
                     
                                                     
  
                                                    
                                                 
                                                       
                                                          
  
                                                           
                                                         
                                                     
                                                                       
                                                        
                                                                
                                                               
                                                  
                                             
                                                             
                                                
                                                    
                                                 
                                                   
  
                                                
                                  
  
                                       
   
gboolean pcv_lio_available(const gchar *root);

   
                         
                                                      
                                         
  
                                                       
                                                   
  
                                                                  
                                     
                                                              
                      
                                          
                                                              
                                                    
                                                        
                                                  
                                 
  
                                        
                                                             
  
                                                             
                                                  
  
                                                  
   
gboolean pcv_lio_ensure_fabric(const gchar *root, GError **error);

                                                                 
  
                                                
                                              
                                                
                                                   
                          
  
                                
                                                                        
                    
                                                   
                                                         
                                         
                                                                          
                                                                            
                                     
                         
  
                                     
                                                                 
                                                                     
                               
  
                                                              
                                                   
                     
                                                             
                                              
                                                                 
                                                                          
                                                               
                         
                                                                   
                                                                    
                                                                   
                                                                               
                                              
                                                      
                                                         
                                                                     
                                                     
                                                                         
                                                                      
                                                                 
                                                      
                                                         
                                                                       
                                                 
                                                                  
                          
  
                                          
                                                                      
                                                        
                                      
  
                                            
                                                       
                                                                      
                                         
  
                                                 
                                                                          
                                                                          
                                                            
                                                    
                                                     
                                                                     
                                       
                                                                       
                                                     
                                              
                                            
        
  
              
                                                      
                                                   
                                                        
                                                         
                                                    
                                                                 
                                 
                                                            
                                                       
                                                      
                                             
                                               
  
                                        
                                                             
                                                        
                                                
                                                           
                          
   

   
                            
                                                              
                                                        
                                                                  
                                                              
                             
                                                                    
                                                
                                                               
                                                                  
                                                       
                                                            
                                                     
                             
                                    
  
                                                      
                                                 
                                                      
                                                     
                                                     
  
                                                        
                                                               
                                                             
                                                         
                                                                
                                         
  
                                      
                                                                       
                                                        
                                              
                                                                     
                                   
  
                                                 
                                                
                                                 
                                                      
              
  
                                                    
                                                       
                                                
                                                   
                         
                                                            
  
                                                            
                                              
   
gboolean pcv_lio_target_create_at(const gchar *root, const gchar *vm_name,
                                  const gchar *zvol_path,
                                  const gchar *chap_user,
                                  const gchar *chap_password,
                                  GError **error);

   
                            
                         
                                                    
                              
  
                                                           
                                             
                                      
                                                 
  
                                                                
                                                   
                              
  
                                                  
   
gboolean pcv_lio_target_delete_at(const gchar *root, const gchar *vm_name,
                                  GError **error);

G_END_DECLS

#endif                           
