                                                                             
                                          
  
                           
                                                   
                                                    
                                        
                                          
  
                                                     
                                                 
                                                   
                                    
  
          
                                                 
                                           
  
                                                 
                                                      
  
            
                                                             
                                                              
                                        
                                                                  
  
                     
                          
                                         
                                                    
  
                       
                                                   
                                                                        
  
                                    
                                                       
                                                                   
                                                    
                                                     
                                          
                                                            
  
          
                                                                       
                                                           
                                          
                         
                                                                       
                                                     
  
           
                                                    
                                                                                

#ifndef PURECVISOR_ANOMALY_DETECTOR_H
#define PURECVISOR_ANOMALY_DETECTOR_H

#include <glib.h>

G_BEGIN_DECLS

   
                                                    
  
                                                     
                                                         
                   
  
                                                                
                                                  
                                                  
                                                                                   
                                                   
                                                             
                                              
   
#define PCV_ANOMALY_AUTO_METRIC_MEM_FULL "purecvisor_cgroup_pressure_memory_full_avg10"

   
                                                      
                                                            
                                             
   
#define PCV_ANOMALY_VM_NAME_MAX 128

                                        
                                                  
void pcv_anomaly_init(void);

                           
                                
void pcv_anomaly_shutdown(void);

   
                        
                                                  
                                 
                                        
                                      
                                      
                                                             
   
void pcv_anomaly_evaluate(void);

   
                               
                                                   
                                        
                                               
                                                        
   
gchar *pcv_anomaly_get_recent_json(void);

   
                              
                                                  
                                            
                                                  
                                          
                          
   
void pcv_anomaly_reset_baseline(void);

                                                                        

   
                               
                                              
                                                      
  
                                                                        
                                            
  
                                                 
                                                    
                                                        
                                
                                                            
  
                                                 
                                                     
                                                    
                                                 
  
                                                        
                                                     
                                                              
                                                                
   
gboolean pcv_anomaly_extract_vm_name(const gchar *labels, gchar *out, gsize out_sz);

   
                             
                                       
  
                                                                    
                                                  
                                                          
                                                      
                                                                    
  
                                                           
                                             
                                                            
                                                           
                                             
  
                                                             
                                  
                                   
                                                           
                                                                  
   
gboolean pcv_anomaly_series_labels(const gchar *line, const gchar *metric_name,
                                   gchar *out, gsize out_sz);

   
                                 
                                                   
                                                  
                                     
  
                                                           
                                                              
                                                          
                                              
  
          
                                                  
                                                         
                                                   
                                                      
                                                               
  
                         
                                                      
                                                  
                                                
                                     
  
                                                             
                                                            
                                                           
                                              
   
gint pcv_anomaly_sync_auto_watches(const gchar *render_text, gint *out_dropped);

                                                                   
                                                             
                                                 
                                             
   
                           
                                              
                                          
   
gint pcv_anomaly_watch_count(void);

G_END_DECLS

#endif                                    
