   
                    
                                                                         
  
                           
                                                   
                                                    
                                        
  
                                                     
                                                        
                                                    
                                                       
                                                    
                                                   
                                                    
                    
  
                                                          
                                                                         
                                                             
                                                                 
                                               
                                                  
                                                         
                                                   
                                                                
                                               
                                                              
         
  
                                            
                                                                          
                                                                     
                                                                      
                                                    
                  
                                                    
                                                           
              
                                                               
                                               
                                                             
                                                
                                                                     
                                              
  
                                      
                                                         
                                                          
  
                                                          
                                                            
                                                       
                                               
                                                  
                                               
   
#ifndef PURECVISOR_PCV_TRACE_H
#define PURECVISOR_PCV_TRACE_H
#include <glib.h>
#include <json-glib/json-glib.h>                                                
G_BEGIN_DECLS

                                                
                                                      
#define PCV_TRACE_MAX_TIMEBOX_SEC 3600
#define PCV_TRACE_OUT_ROOT "/var/run/purecvisor/trace"

   
                                                  
  
                                                        
                                                           
                                     
  
                                                                  
                                                  
                                                 
                                                    
                                                         
                 
   
typedef struct {
    gchar    vm[64];                                                  
    gchar    tenant[64];                      
    gchar    proto[8];                                                            
    gchar    src_ip[46];                                                                    
    gchar    dst_ip[46];                   
    guint    src_port;                                  
    guint    dst_port;                     
    guint    timebox_sec;                                                  
    gboolean overlay;                                                        
} PcvTraceFilter;

   
                             
                                                    
                                                  
                        
                            
  
                                                                       
                                                               
                                                             
                                                               
                                                        
                                              
  
                                             
   
gboolean pcv_trace_filter_validate(const PcvTraceFilter *f, GError **error);

   
                             
                                                
                                                    
                                          
  
                                                     
                                                                     
                                                                 
                                                                 
                                                
                                            
  
                                                      
                                                        
                
   
gchar *pcv_trace_build_pcap_expr(const PcvTraceFilter *f);

   
                        
                                                  
                                      
                                                              
                        
                                                      
                                            
  
                                                      
                                                                       
                                                                    
                                                        
                                          
  
                                                                    
                                                      
   
gchar **pcv_trace_build_argv(const PcvTraceFilter *f, const char *out_dir);

   
                       
                                                      
                                                    
                                                       
                                                      
  
                                                           
                                                  
                                                        
                                                            
                                                   
                        
  
                                                         
                                              
   
gboolean pcv_trace_selfcheck(GError **error);

                                                                             
                                            
  
                                                   
                                                
                                                    
  
                                            
                                                          
                                   
                                                              
                                                     
  
                                          
                                                               
                                                        
                                                           
                                                            
                                         
                                                                                

                                                          
                                                  
                                               
#define PCV_TRACE_RUNNING_MARKER ".running"

   
                         
                                                      
                                   
                                                               
                                                                 
                                
  
                                                    
   
gboolean pcv_trace_try_acquire(void);

   
                     
                                                
                                                            
             
   
void pcv_trace_release(void);

   
                   
                                                      
                                                 
                                       
                             
                                                                   
                                               
                                                          
  
                                                       
                                                               
                                                                  
                                                                  
                                    
  
                                                                     
                            
   
gchar *pcv_trace_start(const PcvTraceFilter *f, const char *admin, GError **error);

   
                  
                                                  
                                        
                                       
                               
  
                                              
                                           
  
                                                                 
   
gboolean pcv_trace_stop(const char *trace_id, GError **error);

   
                    
                                                
                                  
                                                          
  
                                                      
                                                            
                                                            
                           
                                                                       
                            
  
                                                                    
   
JsonObject *pcv_trace_status(const char *trace_id);

                                                                             
                                 
  
                                                   
                                                
                                                   
  
                                                         
                                                                            
                                                   
                                                             
                   
  
                               
                                            
          
                                                             
                                                        
                                                  
                                 
                                                                    
                                                 
                                                       
                                      
                                                         
                     
                                                                                

#define PCV_TRACE_DEFAULT_RETAIN_COUNT 10
#define PCV_TRACE_DEFAULT_RETAIN_MB    512

   
                                                       
                                                       
                                                                
                                                       
                 
                                                        
                          
   
typedef struct {
    gchar   *id;
    gint64   mtime;
    guint64  bytes;
} PcvTraceRetentionEntry;

   
                             
                                                 
                                           
                                                             
                                                     
                                                    
                                                      
                    
                                                  
                                                    
  
                                          
                                                      
  
                                                                    
                                                   
   
GPtrArray *pcv_trace_retention_evict(GPtrArray *entries, guint max_count, guint64 max_bytes);

   
                                  
                                                  
                                  
                                                           
                                                                      
                                                 
                      
  
                                                   
                                             
                                                          
      
   
void pcv_trace_retention_apply_root(const gchar *root);

   
                             
                                                             
                                                                 
                                        
   
void pcv_trace_retention_apply(void);

                                                                             
                                            
  
                                                   
                                                       
                            
  
                    
                                                               
                                                               
                                                        
  
                                     
                                                              
                                                              
                                           
                                                                
                                                  
                                                     
                                                     
                         
                                                                                

   
                       
                                                  
                     
                                                                
                                                                
  
                                                            
                                                                  
                                                                      
                                              
  
                                                                  
   
JsonArray *pcv_trace_list_root(const gchar *root);

   
                  
                                                     
                                                       
                                                                  
   
JsonArray *pcv_trace_list(void);

   
                          
                                                 
                                                   
                                                                           
  
                                                       
                                                                  
                                  
                                                     
                                       
                                                  
  
                                                                    
                             
                                                                                      
                                                                                      
                                                               
                                                      
   
JsonObject *pcv_trace_report_parse(const gchar *print_output);

   
                         
                                                   
                                                     
                                                              
                                         
                          
                                                             
  
                                             
                                                            
                                                           
                                                         
                  
                                                                 
                                                     
                                                            
                                                  
                                                      
                                                   
                                                                         
                                                                   
                                                       
                                                                          
             
  
                                                                         
                      
   
JsonObject *pcv_trace_report_root(const gchar *root, const char *trace_id, GError **error);

   
                    
                                                                     
                          
                               
  
                                                               
                                                   
  
                                                                   
   
JsonObject *pcv_trace_report(const char *trace_id, GError **error);

                                                                             
                                                       
  
                                                   
                                                   
                                                    
                                               
  
                  
                                                         
                                                                        
                                                                  
                                                          
                                                   
                                                  
                        
  
                                         
                                             
                                                  
                              
  
                 
                                                             
                                                           
                                                              
                                                 
                                               
                                                    
                                              
                                                   
  
                                    
                                                           
                                                            
                                                     
                                           
  
                                 
                                                            
                                                      
                                                 
                                                   
                                            
                                                           
                                                      
                                                    
                                 
                                                                                

   
                            
                                                    
                                      
                                                                 
                                                                
  
                                                  
                                                              
                                                
                                                               
          
   
void pcv_trace_purge_all_root(const gchar *root);

   
                       
                                                    
                                            
  
                                                         
                                                       
               
                                                     
                                                             
                                                                   
                                                    
                                                   
                                                             
                                                                
                                                    
                                                    
                                                 
                                                        
                                                             
                                                     
                                                   
                                                                  
                                               
   
void pcv_trace_purge_all(void);

G_END_DECLS
#endif                             
