                          
                                                                       
                                                              
                                                                            
                                                    
 
                      
                                                
                                              
                                          
                                                                      
                                                   
                                                                            
                                                        
[Service]
LimitCORE=0:infinity
