   
                           
                                                                         
  
                           
                                                   
                                                    
                                        
                                                                                     
  
                                                     
                                                             
                                                         
                                                            
                         
  
                       
                                                                         
                                                              
                                                              
  
          
                                                                               
                                                                 
                                            
   
#ifndef PURECVISOR_PCV_SURICATA_IPS_H
#define PURECVISOR_PCV_SURICATA_IPS_H

#include <glib.h>
#include "modules/security/pcv_suricata.h"                         

G_BEGIN_DECLS

                                                           

   
                                    
                            
                                                            
  
                                                          
  
                                                                             
                                                             
   
gchar **pcv_suricata_ips_queue_rule_argv(guint queue_num, gboolean fail_open);

                                                              

   
                           
                                                         
  
                                                                         
                                                                      
                                                 
  
                                                                      
                                                           
                                                                       
                                                          
  
                                                                   
                                                    
                                                                   
  
                                                         
                                                  
   
gboolean pcv_suricata_ips_enable(guint queue_num, gboolean fail_open, GError **error);

   
                            
                                                          
                                                             
                                                   
                                                      
                                                          
                                                        
   
gboolean pcv_suricata_ips_disable(GError **error);

                                                                  
                                   
gboolean pcv_suricata_ips_is_enabled(void);

                                                          
  
                                                       
                                                 
                                                   
                                                    
                                                 
                                                     
  
                                                                        
                                                    
                                        
                                                                 
                                               
   

   
                
                                
                            
  
                                                                  
                                                          
  
                                                                
                                                      
                                                             
                                       
  
                                         
   
typedef gboolean (*PcvIpsExecFn)(const gchar * const *argv, GError **error);

                                                                        
                                                                  
void pcv_suricata_ips_set_exec_hook(PcvIpsExecFn fn);                   

   
                 
                                    
  
                                                               
                                                                     
                                                            
                                                
   
typedef PcvSuricataState (*PcvIpsProbeFn)(void);

                                                                       
void pcv_suricata_ips_set_probe_hook(PcvIpsProbeFn fn);                   

   
                 
                                                         
                                             
   
typedef gboolean (*PcvIpsReadyFn)(GError **error);

                                                                      
                                                             
void pcv_suricata_ips_set_ready_hook(PcvIpsReadyFn fn);                   

   
                                  
                                                                 
                               
  
                                                      
                                      
  
                                                            
                                                                      
                                                     
                                   
  
                                     
   
gboolean pcv_suricata_ips_nfqueue_bound(const gchar *proc_text, guint queue_num);

   
                                  
                                                                 
                               
                                                                            
                                                              
                                                                              
                    
  
                                                     
                                                     
                   
  
                                                                
                                                          
                                                   
                                                         
                                                          
  
                                                          
   
gboolean pcv_suricata_ips_nfqueue_drops(const gchar *proc_text, guint queue_num,
                                        guint64 *queue_dropped, guint64 *user_dropped);

   
                               
                                                                       
                     
  
                                                   
                                                
  
                                                      
                                                                                 
                                                        
              
  
                                                             
                                                                    
                                                      
                                                         
                       
  
                                                                
                                                               
                                   
  
                                                      
                                                      
                                                                 
                                                     
                                                         
                                          
  
                                                                 
                                                           
                                                          
  
                                                             
   
gboolean pcv_suricata_ips_wait_ready(guint timeout_sec, GError **error);

   
                                
                                                       
  
                                                                 
                                            
                                                              
                                                                                 
                              
   
gboolean pcv_suricata_ips_is_degraded(void);

   
                                    
                                                            
  
                                                           
                                                           
                                                 
                                                                         
                                                          
                                                  
                                                                    
                                      
   
void pcv_suricata_ips_shutdown_signal(void);

   
                                     
                                                              
  
                                                               
                                                                
                                                         
               
  
                                                                   
                                                                        
                                                              
                                                       
                                                
  
                                                           
                                                   
   
void pcv_suricata_ips_boot_flush_stale(void);

   
                                          
                                                     
                    
  
                                                           
                                                                  
                                                            
                                 
  
                                                   
                                                    
                                                                 
  
                                                             
                                                       
                                                              
                                                           
                                                 
  
                                                              
                                                       
                                                           
              
   
void pcv_suricata_ips_boot_stop_orphan_unit(void);

                                                      

                                                        
void pcv_suricata_ips_probe_cache_store(PcvSuricataState s);

   
                                         
                                                                  
                                                             
                                                                  
                                                         
   
void pcv_suricata_ips_engine_status_cached(PcvSuricataState *state, gboolean *binary_present);

   
                                
                                                         
                                                                       
                                                                           
                                                          
  
                                        
  
                                                              
                                                                        
                                                           
  
                                                                     
                                                           
                                                                            
                                                                      
                                                        
                                                                      
                                                      
                                                             
                                                      
                                
  
                                                                              
                                                                 
                                                        
                                                                  
                                                       
               
  
                                   
                                                   
                                                     
                                                              
                                                      
                                                                  
                                               
                                                             
                                                              
                                                 
                                                                          
                                                             
                                               
                                                         
  
                                                            
                                                                    
                                                     
                           
   
void pcv_suricata_ips_health_tick(void);

   
                                 
                                                                        
                                                                      
                     
                                                                       
                                                            
                                        
                                                                  
                                                            
                                            
                                                        
                                                                
                                                        
                                                       
   
void pcv_suricata_ips_metrics_tick(void);

G_END_DECLS

#endif                                    
