   
                                 
                                                              
  
                           
                                                   
                                                    
                                        
  
                                                       
                                                      
                                                   
                                                         
                                                    
                 
  
                                                       
                                                                      
                                                     
                                                
                                                    
                            
  
                                                           
                                                 
                                                     
                                                        
                                                 
                                                  
                                           
                                                              
                                                                      
                                                  
                                               
                   
  
                                                   
                                                       
                                                                     
                                                 
                                                
                                           
                                                          
                                                     
                                             
                                             
                                              
                                            
              
  
                               
                                                                    
                                                                           
                                                                        
                                                         
  
                                       
                                 
                                                                      
                                                               
                                                             
                                                  
  
                                                        
                                                                        
                                                               
                                                          
                                                                  
                                                          
                                                 
                                                   
                                                
  
                              
                                                                       
                                                              
                                                                  
                                                
                
                                                           
                                                           
                                                                          
                                                                     
                                                              
                                                       
                                                      
  
                                                
                                                                 
                                                                          
                                                        
                                                      
                                                 
                                                                            
                                                                  
                                       
                                                    
                                                      
                                                           
                                  
                                                                
                                                  
                                                                  
             
   
#ifndef PURECVISOR_PCV_SURICATA_IPS_RULES_H
#define PURECVISOR_PCV_SURICATA_IPS_RULES_H

#include <glib.h>

G_BEGIN_DECLS

                                                          
                                                                      
#define PCV_IPS_RULES_PATH "/var/lib/suricata/suricata-ips.rules"

                                                                         
                                                              
                                           
                                                                     
                                       
#define PCV_SURICATA_IPS_CONFIG_PATH "/etc/suricata/suricata-ips.yaml"

   
                                    
                                                       
                                                                    
                                                             
  
                                                    
                                                         
                                   
  
                              
                                                
                                                          
                                                         
                
                                            
                                                        
                                       
                                                   
                                       
                                                  
                      
  
                                                
                                                           
                                           
                                               
                                                  
                                                             
                                                
                                               
                                                          
                                                 
                                                    
                                 
  
                                                    
  
                                                          
   
gchar *pcv_suricata_ips_rules_transform(const gchar *src, GHashTable *drop_sids,
                                        guint *out_converted);

   
                         
                                                          
                                                       
                            
  
                                                                   
                                                                        
                                                 
  
                       
   
typedef gboolean (*PcvIpsRulesValidateFn)(const gchar *rules_path, GError **error);

   
                       
                            
  
                                                              
                                                                
                                                    
                          
  
                                  
   
typedef gboolean (*PcvIpsRulesReloadFn)(GError **error);

   
                    
                                                              
                                           
                                              
  
                                                           
                                               
                               
   
typedef struct {
    PcvIpsRulesValidateFn validate;
    PcvIpsRulesReloadFn   reload;
} PcvIpsRulesHooks;

   
                                              
                                                       
                                                   
                                      
                                                         
                                                       
                                       
                                                          
                            
  
                                                 
                                               
                                            
  
                     
                                                
                                                   
                                                       
                                                   
                                                                   
                                                        
                                                          
                                                  
                                                          
                                                      
                                                                  
                                                
                                                         
                                                
  
                                            
                                                                        
                                                           
                                                                   
                                                 
  
                                        
                                                                         
                                                                
  
                                                            
   
gboolean pcv_suricata_ips_rules_apply_at(const gchar *src_path, const gchar *out_path,
                                         GHashTable *drop_sids, const gchar *admin,
                                         const PcvIpsRulesHooks *hooks, GError **error);

   
                                
                                    
                                       
                            
  
                                                   
  
                                                                
                                                                 
                                                    
                                               
                                             
  
                                               
  
                                
                                                              
                                                         
                                                     
                                                 
                         
  
                                                  
                                               
                                           
                                                
                                                                 
                                                      
                                          
  
                                                         
                                                          
                                                               
                                                 
                                                        
                                              
                                                              
                                              
                                                
  
                                                      
                                               
  
                                                   
   
gboolean pcv_suricata_ips_rules_apply(GHashTable *drop_sids, const gchar *admin,
                                      GError **error);

   
                                   
                           
                           
  
                                                  
  
                               
                                                           
                                                        
                                                  
                                                             
  
                                              
                                                         
                                                       
                                                            
                                                        
                                                     
                                                        
  
                             
  
                                                          
                                                     
   
gboolean pcv_suricata_ips_rules_stale_at(const gchar *src_path, const gchar *out_path);

   
                                
                                    
  
                                                          
                                                     
                                                                
                                                    
                                                                          
                                          
  
                                                                                         
   
gboolean pcv_suricata_ips_rules_stale(void);

G_END_DECLS

#endif                                          
